-- =====================================================================
-- GENERATED BY MATUGEN — DO NOT EDIT.
-- Source: {{image}}   Mode: {{mode}}
-- Regenerate with: ~/.config/hypr/scripts/wallpaper.sh
-- =====================================================================
--
-- CONTRACT: settings/look_and_feel.lua requires exactly these six keys.
-- Removing one makes col.inactive_border nil and errors on reload.
--
-- hex_stripped omits the leading '#', which is what rgba() needs.
-- The trailing two hex digits are alpha: ee = 93%, 88 = 53%.

return {
    primary    = "rgba({{colors.primary.default.hex_stripped}}ee)",
    secondary  = "rgba({{colors.secondary.default.hex_stripped}}ee)",
    surface    = "rgba({{colors.surface.default.hex_stripped}}ff)",
    on_surface = "rgba({{colors.on_surface.default.hex_stripped}}ff)",
    outline    = "rgba({{colors.outline.default.hex_stripped}}88)",
    error      = "rgba({{colors.error.default.hex_stripped}}ff)",
}
