# SEED PALETTE — overwritten by Matugen on the first wallpaper change.
background            #1e1e2e
foreground            #cdd6f4
cursor                #89b4fa
cursor_text_color     #1e1e2e

selection_background  #89b4fa
selection_foreground  #1e1e2e

url_color             #a6e3a1

active_border_color   #89b4fa
inactive_border_color #45475a

active_tab_background   #89b4fa
active_tab_foreground   #1e1e2e
inactive_tab_background #313244
inactive_tab_foreground #cdd6f4
